---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: debug

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.23"}]
    driver:
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[alfresco-appserver::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: {
      "appserver": {
        "download_artifacts" : true,
        "install_java" : true,
        "install_maven" : true
      }
     }
